[connections.default]
warehouse = "QUICKSTART_WH"
role = "ACCOUNTADMIN"
database = "QUICKSTART_COMMON"
schema = "PUBLIC"
account = "PPJCABF-DA30673"
user = "SVC_SF_DEVOPS_ECY"
password = "dark72Light"
